### ISSUE TITLE
Feedback on the api docs

### ISSUE THREAD

**Issue by wyudong** [primasio/primas-api-doc#1]
Something to make the docs more user-friendly is to write some examples on how to request apis. Some questions the developers will be interested will be:

- What should they prepare at the beginning?
- Any simple examples for creating a user or an article?
- How to request the resource that is just created?

The answers may exist somewhere in primas website. Could you put them in one doc/wiki?

And are you missing the HTTP verbs in all the Primas Node API Document?

**Comment by lencyforce** [comment]
We're still working heavily on the document. It might still take some days to be finished.
