### ISSUE TITLE
502 bad gate way

### ISSUE THREAD

**Issue by samma835** [primasio/primas-api-doc#3]
GET https://staging.primas.io/v3/content/1GFYUNP815RUIFDNNRKLNU78RPCFLNL5DWGT7EXODHFVRCRVXJ

<html>
    <head>
        <title>502 Bad Gateway</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>502 Bad Gateway</h1>
        </center>
        <hr>
        <center>nginx/1.10.3 (Ubuntu)</center>
    </body>
</html>

**Comment by lencyforce** [comment]
#2

**Comment by wyudong** [comment]
It's the test net endpoint, not the main net. The test net is not public now?

**Comment by lencyforce** [comment]
Still needs some days.
