### ISSUE TITLE
使用 Accout.create 出现502错误，请问有什么需要注意的地方？

### ISSUE THREAD

**Issue by MikeOrMilk** [primasio/primas-api-doc#4]
1.我首先运行了   npm install primas-sdk-nodejs --save
2.然后根据 doc api 运行了如下命令
3.运行 js 出现 502 错误
```
var client = new Primas({
	address: "xxxx", // 我的以太坊地址
	passphrase: "xxxx", // 我的以太坊密码
	node: "https://rigel-a.primas.network"
});


client.Account.create(
	{
		name: "userName", // 用户名
		// avatar: "", // Avatar should be a metadata ID which can only be uploaded after the account creation.
		address: "xxxx" // 随机address
	},
	function(err, res) {
	    
		if (err) {
			// handle error
			return;
		}
		
		// The response contains the account id and metadata dna
    console.log(res)
		console.log(res.id);
		console.log(res.dna);
	}
);
```

**Comment by lencyforce** [comment]
API还没有上线主网，测试网上的API也还不完整，本周五完整版本的API会上线测试网

API is not on the main net yet. Even not complete on the test net. The test net will be fully ready by this Friday.

**Comment by wyudong** [comment]
Following creating account code in the getting started guide will response `{ result_code: 404, result_msg: 'parameter version error' }`. @lencyforce

**Comment by koalacxr** [comment]
API 完成了account, content-interaction, content, group，token的部分，其他模块处于开发中。完成的部分可以在staging环境中测试了。

API completes  account, content-interaction, content, group, the sections of token, and others are still under development. It can debug in the staging environment.

**Comment by wyudong** [comment]
@koalacxr 

Added `account.send` but got error:

```
TypeError: Cannot read property 'send' of undefined
    at Object.<anonymous> (/Users/wyudong/Desktop/primas/main.js:24:8)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
``` 

I have keystore directory in the project root. If I type the wrong `passphrase`, it will have `authentication code mismatch` error. So the keystore should have no problem.

Code snippet:

```js
var Primas = require("primas-sdk-nodejs");

var client = new Primas({
    address: "9606487e1badba673e35650558c1907c442538d4",
    passphrase: "********",
    node: "https://staging.primas.io"
});

var account = client.Account.create({
    name: "wyd",
    address: "9606487e1badba673e35650558c1907c442538d4"
});

account.send(function(err, res) {
    if (err) {
        console.log(err)
        return;
    }

    // The response contains the account id and metadata dna
    console.log(res.id);
    console.log(res.dna);
});
```

**Comment by koalacxr** [comment]
Please check api-doc about account:
https://github.com/primasio/primas-api-doc/blob/master/account.md; 

or refer to primas-api-sdk-js: 
https://github.com/primasio/primas-api-sdk-js

**Comment by wyudong** [comment]
@koalacxr Listing the documents doesn't make any sense because they may be outdated already.

I noticed the [getting-started guide is updated](https://github.com/primasio/primas-api-doc/commit/d5c1ed28c2cc4c224649d5b9bf696b414eded66f) several hours ago then I realized the SDK might need update. That's what you should remind the developers of.

I did try to run `npm install` to check if `primas-sdk-nodejs` had any updates, but the package didn't update. I think that is because my dependencies version is like this which will prevent the package from updating to the latest `0.1.3-0`. I don't know much about releasing a node package. Can the semver be set to a wider range?

```
"dependencies": {
    "primas-sdk-nodejs": "^0.1.1-0"
  }
```

For future reference, the `address` should include `0x` in it! So this is the working snippet to creating an account.

```js
var Primas = require("primas-sdk-nodejs");

var client = new Primas({
    address: "0x9606****538d4",
    passphrase: "********",
    node: "https://staging.primas.io"
});

var account = client.Account.create({
    name: "John",
    address: "0x9606****538d4"
});

account.send(function(err, res) {
    if (err) {
        return;
    }
    console.log(res)
});

**Comment by koalacxr** [comment]
@wyudong All development is based on the api documentation. Any changes will update the api documentation first. 

At present, the remaining part of the api is under development, of course, sdk is also in review and add demo. 

The new account system is compatible with the secondary account, so it can't be used directly in the address of Ethereum. The address of the account is displayed in account metadta. 

https://github.com/primasio/primas-api-doc/blob/master/account.md
