### ISSUE TITLE
Is it OK now?

### ISSUE THREAD

**Issue by samma835** [primasio/primas-api-doc#5]
You said it should works at last Friday. But it seems not OK. Need more time?

**Comment by koalacxr** [comment]
API 完成了account, content-interaction, content, group，token的部分，其他模块处于开发中。完成的部分可以在staging环境中测试了。

API completes account, content-interaction, content, group, the sections of token, and others are still under development. It can debug in the staging environment.

**Comment by samma835** [comment]
Cool. Let's try it.

**Comment by samma835** [comment]
The part 6 of Account API is not OK. 

REF:
https://github.com/primasio/primas-api-doc/blob/master/account.md#6-get-account-groups-list

For example, I sent a GET request:
https://staging.primas.io/accounts/800551614ad4e0b656087cc5cbd7e7d6f5dfb81f/groups

return nothing.

**Comment by koalacxr** [comment]
@bullda  
URL Version: 3.0
All requests for the staging environment start with "**https://staging.primas.io/v3**".

So Request URL: https://staging.primas.io/v3/accounts/{account_id}/groups

**Comment by samma835** [comment]
@koalacxr 

Sorry. My fault. It works.

But there's another question. Does this API get the groups who CREATED? How can I get the groups who JOIN?

**Comment by koalacxr** [comment]
@bullda

The group-related api is in "**https://github.com/primasio/primas-api-doc/blob/master/group.md**".

“1. Get group metadata”， this api can get group related info，including “**creator**” , "extra" etc. 
“**extra. members**” ， a list of members joined by this group.


The account-related api is in "**https://github.com/primasio/primas-api-doc/blob/master/account.md**"

"**6. Get account groups list**",  this api can get groups created by this account.

**Comment by samma835** [comment]
@koalacxr 

Thanks for your response. Maybe I didn't speak it clearly. I want to ask that an API to GET ALL THE GROUPS I JOINED, NOT I CREATED.

Two of your API you mentioned can't implement that.

**Comment by koalacxr** [comment]
@bullda Thanks!
Already add joined group in “https://github.com/primasio/primas-api-doc/blob/master/account.md”，“18. Get account joined groups list” .

**Comment by samma835** [comment]
@koalacxr 
Thanks for your help.

Is the server down? All request return 502 issue.

**Comment by koalacxr** [comment]
@bullda 
you try again。
