### ISSUE TITLE
通过node.js的sdk去创建用户时候sign这个方法没有定义啊

### ISSUE THREAD

**Issue by LuoHaoCandy** [primasio/primas-api-doc#7]
var dataJson = account.getRawMetadata(); 
console.log(dataJson)
// do sign now
var signature = sign(dataJson); // this will return signature
// after sign
account.setSignature(signature);
// then send, like the above
account.send();

sign()这个方法在调用的时候返回sign is not defined
应该怎么样修改？

**Comment by LXTyr** [comment]
sign方法是自己实现的签名机的方法，测试环境中我们可以不用签名机，你需要将自己keystore放在项目目录下，或者直接在构造函数里传keystore，详细参数可以在[这个页面](https://github.com/primasio/primas-api-sdk-js#create-a-primas-instance)看到

**Comment by LuoHaoCandy** [comment]
ok，使用前边的send就可以了。
